# Generated by Django 3.0.8 on 2020-08-03 19:51

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapie', '0003_auto_20200801_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='stopien_sprawnosci',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]), null=True, size=None),
        ),
    ]
