# Generated by Django 3.0.8 on 2020-08-03 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapie', '0005_auto_20200803_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='zaawansowanie',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
