# Generated by Django 3.0.8 on 2020-08-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapie', '0007_auto_20200803_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
